import type { GameClass, Item, ClassTierList } from './types';

export const gameClasses: GameClass[] = [
  {
    id: 'wizard',
    name: 'Wizard',
    description: 'A master of arcane arts, wielding powerful spells.',
    kit: 'Wizards rely on a large mana pool and high spell power to deal damage from a distance. They seek items that boost spell power, mana regeneration, and cooldown reduction.',
  },
  {
    id: 'assassin',
    name: 'Assassin',
    description: 'A swift and deadly rogue who excels at single-target elimination.',
    kit: 'Assassins use stealth and high burst damage to take down priority targets. They benefit from items that grant critical strike, attack damage, and on-hit effects.',
  },
  {
    id: 'heavyblade',
    name: 'Heavyblade',
    description: 'A melee powerhouse focused on heavy-hitting attacks.',
    kit: 'The Heavyblade kit revolves around high base damage, critical strikes, and abilities that cleave through multiple enemies. They benefit greatly from items that increase attack damage, critical hit chance, and attack speed.',
  },
  {
    id: 'dancer',
    name: 'Dancer',
    description: 'A nimble and agile fighter who weaves through combat with grace.',
    kit: 'Dancers excel at dodging attacks and dealing rapid, consecutive hits. Their abilities often grant temporary invulnerability or high mobility. They synergize well with on-hit effect items, attack speed, and movement speed.',
  },
  {
    id: 'druid',
    name: 'Druid',
    description: 'A versatile caster who can shapeshift and command nature.',
    kit: 'Druids can switch between healing allies and dealing damage with nature-based spells. They benefit from a mix of spell power, health, and mana regeneration.',
  },
  {
    id: 'spellsword',
    name: 'Spellsword',
    description: 'A hybrid fighter who infuses their weapon with magical energy.',
    kit: 'Spellswords combine melee attacks with magical enhancements. They benefit from items that provide both attack damage and spell power.',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    description: 'A ranged marksman who picks off enemies from extreme distances.',
    kit: 'Snipers specialize in long-range, high-impact shots. Their kit includes abilities that enhance their range and critical damage. They benefit from items increasing attack damage, range, and critical hit chance.',
  },
  {
    id: 'bruiser',
    name: 'Bruiser',
    description: 'A durable fighter who can both take and deal significant damage.',
    kit: 'Bruisers are frontline fighters who can sustain through fights while being a constant threat. They benefit from items that give a mix of health, armor, and attack damage.',
  },
  {
    id: 'defender',
    name: 'Defender',
    description: 'A stalwart protector who excels at shielding allies and controlling enemies.',
    kit: 'Defenders are the ultimate frontline tanks. They use crowd control and high defensive stats to protect their team. They benefit from armor, health, and items that have supportive auras.',
  },
  {
    id: 'ancient',
    name: 'Ancient',
    description: 'A being of immense power from a forgotten era.',
    kit: 'The Ancient possesses unique and powerful abilities that defy conventional classification. Their item synergies are often mysterious and powerful.',
  },
];

export const items: Item[] = [

  {"name": "Raven Grimoire", "description": "Your Special applies Curse Afflicted enemies take 10% extra damage. Duration : 5 seconds .", "category": "Arcane Set", "imageUrl": "https://static.wikitide.net/rnswiki/thumb/6/6f/Spr_item_arcane_0.png/40px-Spr_item_arcane_0.png", "tiers": {"wizard": "NA", "druid": "NA", "spellsword": "NA", "assassin": "NA", "heavyblade": "NA", "dancer": "NA", "sniper": "NA", "bruiser": "NA", "defender": "NA", "ancient": "NA"}},
  {"name": "Blackwing Staff", "description": "Your Primary applies Curse Afflicted enemies take 10% extra damage. Duration : 5 seconds .", "category": "Arcane Set", "imageUrl": "https://static.wikitide.net/rnswiki/thumb/8/85/Spr_item_arcane_1.png/40px-Spr_item_arcane_1.png", "tiers": {"wizard": "NA", "druid": "NA", "spellsword": "NA", "assassin": "NA", "heavyblade": "NA", "dancer": "NA", "sniper": "NA", "bruiser": "NA", "defender": "NA", "ancient": "NA"}},

  {
    id: 'sapphire-brooch',
    name: 'Sapphire Brooch',
    description: 'A beautiful brooch that hums with magical energy.',
    category: 'Rare',
    imageUrl: 'https://picsum.photos/seed/1/400/400',
    tiers: {
      wizard: 'S',
      druid: 'S',
      spellsword: 'S',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'D',
      sniper: 'F',
      bruiser: 'F',
      defender: 'C',
      ancient: 'B',
    },
  },
  {
    id: 'ruby-ring',
    name: 'Ruby Ring',
    description: 'A ring that glows with an inner fire.',
    category: 'Rare',
    imageUrl: 'https://picsum.photos/seed/2/400/400',
    tiers: {
      wizard: 'F',
      assassin: 'S',
      heavyblade: 'S',
      dancer: 'A',
      druid: 'D',
      spellsword: 'S',
      sniper: 'S',
      bruiser: 'A',
      defender: 'D',
      ancient: 'B',
    },
  },
  {
    id: 'swift-boots',
    name: 'Swift Boots',
    description: 'These boots feel lighter than air.',
    category: 'Common',
    imageUrl: 'https://picsum.photos/seed/3/400/400',
    tiers: {
      wizard: 'B',
      assassin: 'A',
      heavyblade: 'B',
      dancer: 'S',
      druid: 'C',
      spellsword: 'A',
      sniper: 'A',
      bruiser: 'B',
      defender: 'B',
      ancient: 'C',
    },
  },
  {
    id: 'ancient-tome',
    name: 'Ancient Tome',
    description: 'A book filled with forgotten incantations.',
    category: 'Legendary',
    imageUrl: 'https://picsum.photos/seed/4/400/400',
    tiers: {
      wizard: 'S',
      druid: 'A',
      spellsword: 'B',
      ancient: 'S',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
    },
  },
  {
    id: 'berserkers-greataxe',
    name: "Berserker's Greataxe",
    description: 'An axe that seems to hunger for battle.',
    category: 'Legendary',
    imageUrl: 'https://picsum.photos/seed/5/400/400',
    tiers: {
      heavyblade: 'S',
      bruiser: 'S',
      spellsword: 'B',
      dancer: 'C',
      assassin: 'C',
      sniper: 'D',
      ancient: 'D',
      wizard: 'F',
      druid: 'F',
      defender: 'F',
    },
  },
  {
    id: 'moon-glaive',
    name: 'Moon Glaive',
    description: "A silent weapon that strikes like moonlight.",
    category: 'Rare',
    imageUrl: 'https://picsum.photos/seed/6/400/400',
    tiers: {
      dancer: 'S',
      assassin: 'B',
      spellsword: 'A',
      sniper: 'B',
      heavyblade: 'B',
      druid: 'D',
      bruiser: 'C',
      defender: 'C',
      ancient: 'A',
      wizard: 'D',
    },
  },
  {
    id: 'cursed-idol',
    name: 'Cursed Idol',
    description: 'A unsettling idol that whispers promises of power.',
    category: 'Cursed',
    imageUrl: 'https://picsum.photos/seed/7/400/400',
    tiers: {
      ancient: 'S',
      assassin: 'A',
      heavyblade: 'A',
      sniper: 'C',
      bruiser: 'C',
      wizard: 'C',
      dancer: 'B',
      spellsword: 'D',
      druid: 'F',
      defender: 'F',
    },
  },
  {
    id: 'leather-armor',
    name: 'Leather Armor',
    description: 'Simple but effective protection.',
    category: 'Common',
    imageUrl: 'https://picsum.photos/seed/8/400/400',
    tiers: {
      defender: 'S',
      bruiser: 'A',
      druid: 'B',
      dancer: 'B',
      assassin: 'D',
      heavyblade: 'C',
      sniper: 'D',
      spellsword: 'C',
      wizard: 'F',
      ancient: 'F',
    },
  },
  {
    id: 'mages-circlet',
    name: "Mage's Circlet",
    description: 'A circlet that focuses arcane energies.',
    category: 'Common',
    imageUrl: 'https://picsum.photos/seed/9/400/400',
    tiers: {
      wizard: 'A',
      druid: 'A',
      spellsword: 'C',
      ancient: 'D',
      sapphire: 'S',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
    },
  },
  {
    id: 'longbow',
    name: "Longbow",
    description: 'A standard issue longbow for archers.',
    category: 'Common',
    imageUrl: 'https://picsum.photos/seed/10/400/400',
    tiers: {
      sniper: 'S',
      dancer: 'A',
      heavyblade: 'D',
      assassin: 'D',
      bruiser: 'D',
      defender: 'D',
      wizard: 'F',
      druid: 'F',
      spellsword: 'F',
      ancient: 'F',
    },
  },
];


export const classTiers: ClassTierList = {
  dancer: {
    'swift-boots': 'S',
    'moon-glaive': 'S',
    'ruby-ring': 'A',
    'longbow': 'A',
    'cursed-idol': 'B',
    'leather-armor': 'B',
    'berserkers-greataxe': 'C',
    'sapphire-brooch': 'D',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  wizard: {
    'ancient-tome': 'S',
    'sapphire-brooch': 'S',
    'mages-circlet': 'A',
    'swift-boots': 'B',
    'cursed-idol': 'C',
    'moon-glaive': 'D',
    'ruby-ring': 'F',
    'berserkers-greataxe': 'F',
    'leather-armor': 'F',
    'longbow': 'F',
  },
  assassin: {
    'ruby-ring': 'S',
    'swift-boots': 'A',
    'cursed-idol': 'A',
    'moon-glaive': 'B',
    'berserkers-greataxe': 'C',
    'leather-armor': 'D',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  heavyblade: {
    'berserkers-greataxe': 'S',
    'ruby-ring': 'S',
    'cursed-idol': 'A',
    'swift-boots': 'B',
    'moon-glaive': 'B',
    'leather-armor': 'C',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  druid: {
    'sapphire-brooch': 'S',
    'ancient-tome': 'A',
    'mages-circlet': 'A',
    'leather-armor': 'B',
    'swift-boots': 'C',
    'ruby-ring': 'D',
    'moon-glaive': 'D',
    'longbow': 'F',
    'berserkers-greataxe': 'F',
    'cursed-idol': 'F',
  },
  spellsword: {
    'ruby-ring': 'S',
    'sapphire-brooch': 'S',
    'swift-boots': 'A',
    'moon-glaive': 'A',
    'ancient-tome': 'B',
    'berserkers-greataxe': 'B',
    'mages-circlet': 'C',
    'leather-armor': 'C',
    'cursed-idol': 'D',
    'longbow': 'F',
  },
  sniper: {
    'longbow': 'S',
    'ruby-ring': 'S',
    'swift-boots': 'A',
    'moon-glaive': 'B',
    'cursed-idol': 'C',
    'leather-armor': 'D',
    'berserkers-greataxe': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  bruiser: {
    'berserkers-greataxe': 'S',
    'leather-armor': 'A',
    'ruby-ring': 'A',
    'swift-boots': 'B',
    'moon-glaive': 'C',
    'cursed-idol': 'C',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  defender: {
    'leather-armor': 'S',
    'swift-boots': 'B',
    'sapphire-brooch': 'C',
    'moon-glaive': 'C',
    'ruby-ring': 'D',
    'longbow': 'D',
    'berserkers-greataxe': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
    'cursed-idol': 'F',
  },
  ancient: {
    'cursed-idol': 'S',
    'ancient-tome': 'S',
    'moon-glaive': 'A',
    'sapphire-brooch': 'B',
    'ruby-ring': 'B',
    'swift-boots': 'C',
    'berserkers-greataxe': 'D',
    'mages-circlet': 'D',
    'leather-armor': 'F',
    'longbow': 'F',
  },
};
