
import type { GameClass, Item, ClassTierList } from './types';

export const gameClasses: GameClass[] = [
  {
    id: 'wizard',
    name: 'Wizard',
    description: 'A master of arcane arts, wielding powerful spells.',
    kit: 'Wizards rely on a large mana pool and high spell power to deal damage from a distance. They seek items that boost spell power, mana regeneration, and cooldown reduction.',
  },
  {
    id: 'assassin',
    name: 'Assassin',
    description: 'A swift and deadly rogue who excels at single-target elimination.',
    kit: 'Assassins use stealth and high burst damage to take down priority targets. They benefit from items that grant critical strike, attack damage, and on-hit effects.',
  },
  {
    id: 'heavyblade',
    name: 'Heavyblade',
    description: 'A melee powerhouse focused on heavy-hitting attacks.',
    kit: 'The Heavyblade kit revolves around high base damage, critical strikes, and abilities that cleave through multiple enemies. They benefit greatly from items that increase attack damage, critical hit chance, and attack speed.',
  },
  {
    id: 'dancer',
    name: 'Dancer',
    description: 'A nimble and agile fighter who weaves through combat with grace.',
    kit: 'Dancers excel at dodging attacks and dealing rapid, consecutive hits. Their abilities often grant temporary invulnerability or high mobility. They synergize well with on-hit effect items, attack speed, and movement speed.',
  },
  {
    id: 'druid',
    name: 'Druid',
    description: 'A versatile caster who can shapeshift and command nature.',
    kit: 'Druids can switch between healing allies and dealing damage with nature-based spells. They benefit from a mix of spell power, health, and mana regeneration.',
  },
  {
    id: 'spellsword',
    name: 'Spellsword',
    description: 'A hybrid fighter who infuses their weapon with magical energy.',
    kit: 'Spellswords combine melee attacks with magical enhancements. They benefit from items that provide both attack damage and spell power.',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    description: 'A ranged marksman who picks off enemies from extreme distances.',
    kit: 'Snipers specialize in long-range, high-impact shots. Their kit includes abilities that enhance their range and critical damage. They benefit from items increasing attack damage, range, and critical hit chance.',
  },
  {
    id: 'bruiser',
    name: 'Bruiser',
    description: 'A durable fighter who can both take and deal significant damage.',
    kit: 'Bruisers are frontline fighters who can sustain through fights while being a constant threat. They benefit from items that give a mix of health, armor, and attack damage.',
  },
  {
    id: 'defender',
    name: 'Defender',
    description: 'A stalwart protector who excels at shielding allies and controlling enemies.',
    kit: 'Defenders are the ultimate frontline tanks. They use crowd control and high defensive stats to protect their team. They benefit from armor, health, and items that have supportive auras.',
  },
  {
    id: 'ancient',
    name: 'Ancient',
    description: 'A being of immense power from a forgotten era.',
    kit: 'The Ancient possesses unique and powerful abilities that defy conventional classification. Their item synergies are often mysterious and powerful.',
  },
];

export const items: Item[] = [
  {"name": "Ancient Tome", "description": "blank", "imageUrl": "/items/ancient-tome.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Arcane Ring", "description": "blank", "imageUrl": "/items/arcane-ring.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Berserkers Greataxe", "description": "blank", "imageUrl": "/items/berserkers-greataxe.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Blackwing Staff", "description": "blank", "imageUrl": "/items/blackwing-staff.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Blood Dagger", "description": "blank", "imageUrl": "/items/blood-dagger.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Cursed Idol", "description": "blank", "imageUrl": "/items/cursed-idol.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Dancers Fan", "description": "blank", "imageUrl": "/items/dancers-fan.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Draining Charm", "description": "blank", "imageUrl": "/items/draining-charm.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Elven Bow", "description": "blank", "imageUrl": "/items/elven-bow.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Leather Armor", "description": "blank", "imageUrl": "/items/leather-armor.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Longbow", "description": "blank", "imageUrl": "/items/longbow.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Mages Circlet", "description": "blank", "imageUrl": "/items/mages-circlet.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Moon Glaive", "description": "blank", "imageUrl": "/items/moon-glaive.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Natures Charm", "description": "blank", "imageUrl": "/items/natures-charm.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Raven Grimoire", "description": "blank", "imageUrl": "/items/raven-grimoire.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Ruby Ring", "description": "blank", "imageUrl": "/items/ruby-ring.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Sapphire Brooch", "description": "blank", "imageUrl": "/items/sapphire-brooch.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Steel Greataxe", "description": "blank", "imageUrl": "/items/steel-greataxe.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Swift Boots", "description": "blank", "imageUrl": "/items/swift-boots.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}},
  {"name": "Youkai Bracelet", "description": "blank", "imageUrl": "/items/youkai-bracelet.png", "tiers": {"wizard": "F", "druid": "F", "spellsword": "F", "assassin": "F", "heavyblade": "F", "dancer": "F", "sniper": "F", "bruiser": "F", "defender": "F", "ancient": "F"}}
].sort((a, b) => a.name.localeCompare(b.name));


export const classTiers: ClassTierList = {
  dancer: {
    'swift-boots': 'S',
    'moon-glaive': 'S',
    'ruby-ring': 'A',
    'longbow': 'A',
    'cursed-idol': 'B',
    'leather-armor': 'B',
    'berserkers-greataxe': 'C',
    'sapphire-brooch': 'D',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  wizard: {
    'ancient-tome': 'S',
    'sapphire-brooch': 'S',
    'mages-circlet': 'A',
    'swift-boots': 'B',
    'cursed-idol': 'C',
    'moon-glaive': 'D',
    'ruby-ring': 'F',
    'berserkers-greataxe': 'F',
    'leather-armor': 'F',
    'longbow': 'F',
  },
  assassin: {
    'ruby-ring': 'S',
    'swift-boots': 'A',
    'cursed-idol': 'A',
    'moon-glaive': 'B',
    'berserkers-greataxe': 'C',
    'leather-armor': 'D',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  heavyblade: {
    'berserkers-greataxe': 'S',
    'ruby-ring': 'S',
    'cursed-idol': 'A',
    'swift-boots': 'B',
    'moon-glaive': 'B',
    'leather-armor': 'C',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  druid: {
    'sapphire-brooch': 'S',
    'ancient-tome': 'A',
    'mages-circlet': 'A',
    'leather-armor': 'B',
    'swift-boots': 'C',
    'ruby-ring': 'D',
    'moon-glaive': 'D',
    'longbow': 'F',
    'berserkers-greataxe': 'F',
    'cursed-idol': 'F',
  },
  spellsword: {
    'ruby-ring': 'S',
    'sapphire-brooch': 'S',
    'swift-boots': 'A',
    'moon-glaive': 'A',
    'ancient-tome': 'B',
    'berserkers-greataxe': 'B',
    'mages-circlet': 'C',
    'leather-armor': 'C',
    'cursed-idol': 'D',
    'longbow': 'F',
  },
  sniper: {
    'longbow': 'S',
    'ruby-ring': 'S',
    'swift-boots': 'A',
    'moon-glaive': 'B',
    'cursed-idol': 'C',
    'leather-armor': 'D',
    'berserkers-greataxe': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  bruiser: {
    'berserkers-greataxe': 'S',
    'leather-armor': 'A',
    'ruby-ring': 'A',
    'swift-boots': 'B',
    'moon-glaive': 'C',
    'cursed-idol': 'C',
    'longbow': 'D',
    'sapphire-brooch': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
  },
  defender: {
    'leather-armor': 'S',
    'swift-boots': 'B',
    'sapphire-brooch': 'C',
    'moon-glaive': 'C',
    'ruby-ring': 'D',
    'longbow': 'D',
    'berserkers-greataxe': 'F',
    'ancient-tome': 'F',
    'mages-circlet': 'F',
    'cursed-idol': 'F',
  },
  ancient: {
    'cursed-idol': 'S',
    'ancient-tome': 'S',
    'moon-glaive': 'A',
    'sapphire-brooch': 'B',
    'ruby-ring': 'B',
    'swift-boots': 'C',
    'berserkers-greataxe': 'D',
    'mages-circlet': 'D',
    'leather-armor': 'F',
    'longbow': 'F',
  },
};
