import type { Item } from './types';
const cacheBust = `?t=1719280457`;

export const items: Item[] = [
  {
    name: 'Raven Grimoire',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/6/6f/Spr_item_arcane_0.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Blackwing Staff',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/8/85/Spr_item_arcane_1.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Curse Talon',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/2/27/Spr_item_arcane_2.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Darkmagic Blade',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/8/8b/Spr_item_arcane_3.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Witchs Cloak',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/1/18/Spr_item_arcane_4.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Crowfeather Hairpin',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/6/6f/Spr_item_arcane_5.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Redblack Ribbon',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/7/78/Spr_item_arcane_6.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Opal Necklace',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/a/a2/Spr_item_arcane_7.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'youkai_bracelet',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/e/e5/Spr_item_youkai_1.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'vega_spear',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/0/09/Spr_item_youkai_6.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'usagi_kamen',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/f/f5/Spr_item_youkai_4.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'red_tanzaku',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/9/95/Spr_item_youkai_5.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'oni_staff',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/6/6c/Spr_item_youkai_2.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'kyou_no_omikuji',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/7/73/Spr_item_youkai_0.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'kappa_shield',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/5/5b/Spr_item_youkai_3.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'altair_dagger',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/3/36/Spr_item_youkai_7.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Thiefs Coat',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/3/34/Spr_item_wind_7.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Sparrow Feather',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/3/30/Spr_item_wind_5.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Shinsoku Katana',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/1/15/Spr_item_wind_3.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
  {
    name: 'Pidgeon Bow',
    description: 'blank',
    imageUrl: `https://static.wikitide.net/rnswiki/1/13/Spr_item_wind_2.png${cacheBust}`,
    tiers: {
      wizard: 'F',
      assassin: 'F',
      heavyblade: 'F',
      dancer: 'F',
      druid: 'F',
      spellsword: 'F',
      sniper: 'F',
      bruiser: 'F',
      defender: 'F',
      ancient: 'F',
    },
  },
].sort((a, b) => a.name.localeCompare(b.name));
