import type { GameClass, Item } from './types';
const cacheBust = `?t=${new Date().getTime()}`;

export const gameClasses: GameClass[] = [
  {
    id: 'wizard',
    name: 'Wizard',
  },
  {
    id: 'assassin',
    name: 'Assassin',
  },
  {
    id: 'heavyblade',
    name: 'Heavyblade',
  },
  {
    id: 'dancer',
    name: 'Dancer',
  },
  {
    id: 'druid',
    name: 'Druid',
  },
  {
    id: 'spellsword',
    name: 'Spellsword',
  },
  {
    id: 'sniper',
    name: 'Sniper',
  },
  {
    id: 'bruiser',
    name: 'Bruiser',
  },
  {
    id: 'defender',
    name: 'Defender',
  },
  {
    id: 'ancient',
    name: 'Ancient',
  },
];

export const items: Item[] = 
  [{
      "name": "Raven Grimoire",
      "description": "Your Special applies Curse.",
      "imageUrl": "https://static.wikitide.net/rnswiki/6/6f/Spr_item_arcane_0.png",
      "tiers": {
		"wizard": "C",
		"assassin": "B",
		"heavyblade": "C",
		"dancer": "A",
		"druid": "A",
		"spellsword": "S",
		"sniper": "S",
		"bruiser": "D",
		"defender": "A",
		"ancient": "C",
      }
    },
{
      "name": "Blackwing Staff",
      "description": "Your Primary applies Curse.",
      "imageUrl": "https://static.wikitide.net/rnswiki/8/85/Spr_item_arcane_1.png",
      "tiers": {
        "wizard": "B",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "A",
		"druid": "B",
		"spellsword": "A",
		"sniper": "A",
		"bruiser": "A",
		"defender": "A",
		"ancient": "C",
      }
    },
{
      "name": "Curse Talon",
      "description": "Your Secondary applies Curse.",
      "imageUrl": "https://static.wikitide.net/rnswiki/2/27/Spr_item_arcane_2.png",
      "tiers": {
        "wizard": "B",
		"assassin": "B",
		"heavyblade": "C",
		"dancer": "A",
		"druid": "A",
		"spellsword": "A",
		"sniper": "A",
		"bruiser": "C",
		"defender": "A",
		"ancient": "B",
      }
    },
{
      "name": "Darkmagic Blade",
      "description": "Every 10s, slices the air around you dealing 300 damage and applying Curse to nearby enemies.",
      "imageUrl": "https://static.wikitide.net/rnswiki/8/8b/Spr_item_arcane_3.png",
      "tiers": {
        "wizard": "C",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "A",
		"druid": "B",
		"spellsword": "B",
		"sniper": "B",
		"bruiser": "B",
		"defender": "B",
		"ancient": "B",
      }
    },
{
      "name": "Witch's Cloak",
      "description": "Your Secondary deals 10% more damage. Debuffs you place deal 70% more damage. Slightly increases movement speed.",
      "imageUrl": "https://static.wikitide.net/rnswiki/1/18/Spr_item_arcane_4.png",
      "tiers": {
        "wizard": "C",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "B",
		"druid": "C",
		"spellsword": "B",
		"sniper": "S",
		"bruiser": "C",
		"defender": "B",
		"ancient": "B",
      }
    },
{
      "name": "Crowfeather Hairpin",
      "description": "Increases Special damage by 20%. When you place a debuff on an opponent, your Special has a 50% chance of resetting.",
      "imageUrl": "https://static.wikitide.net/rnswiki/6/6f/Spr_item_arcane_5.png",
      "tiers": {
        "wizard": "A",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "C",
		"druid": "C",
		"spellsword": "S",
		"sniper": "B",
		"bruiser": "C",
		"defender": "A",
		"ancient": "A",
      }
    },
{
      "name": "Redblack Ribbon",
      "description": "You deal 5% more damage. When you place a debuff on an opponent, your Defensive has a 50% chance of resetting.",
      "imageUrl": "https://static.wikitide.net/rnswiki/7/78/Spr_item_arcane_6.png",
      "tiers": {
        "wizard": "C",
		"assassin": "C",
		"heavyblade": "C",
		"dancer": "D",
		"druid": "C",
		"spellsword": "A",
		"sniper": "A",
		"bruiser": "C",
		"defender": "A",
		"ancient": "C",
      }
    },
{
      "name": "Opal Necklace",
      "description": "When you use your Defensive, apply Curse to all enemies.",
      "imageUrl": "https://static.wikitide.net/rnswiki/a/a2/Spr_item_arcane_7.png",
      "tiers": {
        "wizard": "B",
		"assassin": "S",
		"heavyblade": "C",
		"dancer": "A",
		"druid": "B",
		"spellsword": "B",
		"sniper": "A",
		"bruiser": "B",
		"defender": "F",
		"ancient": "F",
      }
    },
{
        "name": "Sleeping Greatbow",
        "description": "Every 6s, fires a slow-moving projectile at your targeted enemy that deals 200 damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/0f/Spr_item_night_0.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Crescentmoon Dagger",
        "description": "Every 10s, your Secondary will deal an additional 400 damage on hit.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/1b/Spr_item_night_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "C",
			"defender": "A",
			"ancient": "A",
        }
      },
{
        "name": "Lullaby Harp",
        "description": "Every 10s, resets Defensive cooldowns for you and all allies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f9/Spr_item_night_2.png",
        "tiers": {
			"wizard": "S",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "S",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "A",
			"defender": "A",
			"ancient": "A",
        }
      },
{
        "name": "Nightstar Grimoire",
        "description": "Every 25s, deal 900 damage to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f2/Spr_item_night_3.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Moon Pendant",
        "description": "Every 12s, using your Special will deal 400 damage to enemies in a moderate radius around you.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/1c/Spr_item_night_4.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Pajama Hat",
        "description": "Defensive and loot cooldowns are shortened by 2s.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/20/Spr_item_night_5.png",
        "tiers": {
			"wizard": "A",
			"assassin": "S",
			"heavyblade": "A",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Stuffed Rabbit",
        "description": "Increases Special damage by 20%. Every 12s, using your Special will grant you invulnerability for 3s. Starts battle on cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d7/Spr_item_night_6.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "F",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Nightingale Gown",
        "description": "Every 15s, Omega Charge attacks deal 3.0x damage when you use your Special.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f1/Spr_item_night_7.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "S",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "D",
			"defender": "S",
			"ancient": "B",
        }
      },
{
	  "name": "Eternity Flute",
	  "description": "Every 12s, grants Haste to all allies.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/9/95/Spr_item_timespace_0.png",
	  "tiers": {
		"wizard": "A",
		"assassin": "B",
		"heavyblade": "C",
		"dancer": "A",
		"druid": "C",
		"spellsword": "C",
		"sniper": "B",
		"bruiser": "B",
		"defender": "B",
		"ancient": "B",
        }
	},
{
	  "name": "Timewarp Wand",
	  "description": "Your Secondary has a 40% chance of giving you Haste.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/7/79/Spr_item_timespace_1.png",
	  "tiers": {
		"wizard": "B",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "S",
		"druid": "C",
		"spellsword": "C",
		"sniper": "D",
		"bruiser": "B",
		"defender": "B",
		"ancient": "C",

	  }
	},
{
	  "name": "Chrome Shield",
	  "description": "Using your Defensive will grant you Haste.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/f/f3/Spr_item_timespace_2.png",
	  "tiers": {
		"wizard": "S",
		"assassin": "S",
		"heavyblade": "A",
		"dancer": "A",
		"druid": "C",
		"spellsword": "B",
		"sniper": "C",
		"bruiser": "A",
		"defender": "C",
		"ancient": "C",

	  }
	},
{
	  "name": "Clockwork Tome",
	  "description": "Your Special has a 50% chance of giving you Haste.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/a/a2/Spr_item_timespace_3.png",
	  "tiers": {
		"wizard": "C",
		"assassin": "A",
		"heavyblade": "B",
		"dancer": "A",
		"druid": "C",
		"spellsword": "A",
		"sniper": "C",
		"bruiser": "D",
		"defender": "B",
		"ancient": "D",

	  }
	},
{
	  "name": "Metronome Boots",
	  "description": "Your GCDs become 1.1s. Also moderately increases movement speed.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/d/d2/Spr_item_timespace_4.png",
	  "tiers": {
		"wizard": "B",
		"assassin": "C",
		"heavyblade": "D",
		"dancer": "D",
		"druid": "B",
		"spellsword": "D",
		"sniper": "D",
		"bruiser": "F",
		"defender": "A",
		"ancient": "D",

	  }
	},
{
	  "name": "Timemage Cap",
	  "description": "Cooldowns less than or equal to 10s become 5s.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/1/12/Spr_item_timespace_5.png",
	  "tiers": {
		"wizard": "D",
		"assassin": "B",
		"heavyblade": "D",
		"dancer": "D",
		"druid": "B",
		"spellsword": "S",
		"sniper": "S",
		"bruiser": "D",
		"defender": "C",
		"ancient": "D",

	  }
	},
{
	  "name": "Starry Cloak",
	  "description": "Your Defensive's cooldown becomes 10s. Slightly increases movement speed.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/6/6d/Spr_item_timespace_6.png",
	  "tiers": {
		"wizard": "S",
		"assassin": "B",
		"heavyblade": "B",
		"dancer": "A",
		"druid": "C",
		"spellsword": "A",
		"sniper": "C",
		"bruiser": "D",
		"defender": "C",
		"ancient": "D",

	  }
	},
{
	  "name": "Gemini Necklace",
	  "description": "Your Special and Defensive have a 30% chance of instantly resetting when used.",
	  "imageUrl": "https://static.wikitide.net/rnswiki/5/5a/Spr_item_timespace_7.png",
	  "tiers": {
		"wizard": "A",
		"assassin": "B",
		"heavyblade": "C",
		"dancer": "A",
		"druid": "B",
		"spellsword": "S",
		"sniper": "B",
		"bruiser": "D",
		"defender": "A",
		"ancient": "C",

	  }
	},
{
        "name": "Hawkfeather Fan",
        "description": "Reduces your Special's cooldown by 2s.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c4/Spr_item_wind_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "D",
			"druid": "B",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",	
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Windbite Dagger",
        "description": "Your Secondary's GCD becomes 0.5s, but its damage is reduced by 60%.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/ef/Spr_item_wind_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "A",
			"dancer": "S",
			"druid": "D",
			"spellsword": "D",
			"sniper": "F",
			"bruiser": "A",
			"defender": "A",
			"ancient": "F",
        }
      },
{
        "name": "Pidgeon Bow",
        "description": "Every 3s, fires a projectile at your targeted enemy that deals 70 damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/13/Spr_item_wind_2.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Shinsoku Katana",
        "description": "Your Primary's GCD has a 50% chance to be 0.8s instead of its normal amount.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/15/Spr_item_wind_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "S",
			"druid": "B",
			"spellsword": "D",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Eaglewing Charm",
        "description": "All your abilities deal 20 more damage. Significantly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/95/Spr_item_wind_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Sparrow Feather",
        "description": "Deals 50 damage to all enemies when your Primary or Secondary is used.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/30/Spr_item_wind_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "D",
			"bruiser": "B",
			"defender": "C",
			"ancient": "D",
        }
      },
{
        "name": "Winged Cap",
        "description": "Grants a brief speed boost when your Secondary is used. Moderately increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/20/Spr_item_wind_6.png",
        "tiers": {
			"wizard": "F",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Thief's Coat",
        "description": "Every 10s, gain Vanish and evade attacks until you use an attack. Increases damage dealt by 30% for 3 seconds. Gain a brief speed boost when you use your Special. Moderately increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/34/Spr_item_wind_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Vampiric Dagger",
        "description": "Your Secondary inflicts Bleed. Afflicted enemies take extra damage from your abilities or loot effects. Extra damage is reduced for allies' hits. Strength: 20. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/ce/Spr_item_bloodwolf_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "A",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "A",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Bloody Bandage",
        "description": "When you use your Defensive, apply Bleed. Afflicted enemies take extra damage from your abilities or loot effects. Extra damage is reduced for allies' hits. Strength: 20. Duration: 10 seconds to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/35/Spr_item_bloodwolf_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "A",
			"defender": "C",
			"ancient": "S",
        }
      },
{
        "name": "Leech Staff",
        "description": "Your Primary inflicts Bleed. Afflicted enemies take extra damage from your abilities or loot effects. Extra damage is reduced for allies' hits. Strength: 20. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a9/Spr_item_bloodwolf_2.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Bloodhound Greatsword",
        "description": "Every 12s, slices the air around you dealing 380 damage and applying Bleed. Afflicted enemies take extra damage from your abilities or loot effects. Extra damage is reduced for allies' hits. Strength: 20. Duration: 10 seconds to nearby enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/13/Spr_item_bloodwolf_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "A",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Reaper Cloak",
        "description": "Your Defensive additionally deals 100 damage 3 times to enemies facing away from you. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/45/Spr_item_bloodwolf_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Bloodflower Brooch",
        "description": "All abilities deal 40 damage 2 times to enemies facing away from you.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f1/Spr_item_bloodwolf_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "C",
			"spellsword": "S",
			"sniper": "C",
			"bruiser": "B",
			"defender": "C",
			"ancient": "A",
        }
      },
{
        "name": "Wolf Hood",
        "description": "Every 6 seconds when you use your Primary, deal 250 damage to enemies facing away from you. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/48/Spr_item_bloodwolf_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Blood Vial",
        "description": "At the start of each fight, inflict all enemies with Sap. Afflicted enemies take extra damage from abilities or loot effects. Strength: 20. Duration: 99 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/b6/Spr_item_bloodwolf_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "A",
			"spellsword": "A",
			"sniper": "A",
			"bruiser": "A",
			"defender": "D",
			"ancient": "B",
        }
      },
{
        "name": "Black Wakizashi",
        "description": "Your Primary has a 30% chance of dealing an additional 3 blows, dealing 50 damage each, in a radius around your target enemy.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d6/Spr_item_assassin_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Throwing Dagger",
        "description": "Every 5s, fires a projectile at your targeted enemy that deals 120 damage. Cooldown resets every time you use your Special.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a2/Spr_item_assassin_1.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "A",
			"sniper": "A",
			"bruiser": "D",
			"defender": "B",
			"ancient": "F",
        }
      },
{
        "name": "Assassin's Knife",
        "description": "Your Secondary has a 30% chance of dealing an additional 2 blows, dealing 50 damage each, in a radius around your target enemy.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/ed/Spr_item_assassin_2.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "D",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "B",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Ninjutsu Scroll",
        "description": "Your Special has a 30% chance of dealing an additional 3 blows, dealing 150 damage each, in a radius around your target enemy.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d8/Spr_item_assassin_3.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "C",
			"spellsword": "A",
			"sniper": "A",
			"bruiser": "D",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Shadow Bracelet",
        "description": "Abilities and loot that hit more than once deal 30 more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/bb/Spr_item_assassin_4.png",
        "tiers": {
			"wizard": "F",
			"assassin": "S",
			"heavyblade": "F",
			"dancer": "B",
			"druid": "A",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Ninja Robe",
        "description": "When a % chance succeeds, erase projectiles around you and Vanish and evade attacks until you use an attack. Increases damage dealt by 30% for 3 seconds. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d2/Spr_item_assassin_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "F",
			"dancer": "A",
			"druid": "D",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Kunoichi Hood",
        "description": "Your abilities do 15 more damage. Your loot does 50 more damage. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/92/Spr_item_assassin_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "A",
			"dancer": "B",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Shinobi Tabi",
        "description": "Standing still will cause you to Vanish and evade attacks until you use an attack. Increases damage dealt by 30% for 5 seconds and resets your Special. Available every 8s. Starts battle on cooldown. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/31/Spr_item_assassin_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "S",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "C",
			"defender": "A",
			"ancient": "S",
        }
      },
{
        "name": "Dragonhead Spear",
        "description": "Your Primary is 40% more powerful, but gains a cooldown of 3s. Also slightly reduces movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/12/Spr_item_rockdragon_0.png",
        "tiers": {
			"wizard": "F",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "F",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Granite Greatsword",
        "description": "Every 16s, slices a large radius around you dealing 700 damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/df/Spr_item_rockdragon_1.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "A",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Greysteel Shield",
        "description": "Your Defensive has a 30% larger radius. Invulnerability effects last 1s longer.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c9/Spr_item_rockdragon_2.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Stonebreaker Staff",
        "description": "Your Special's cooldown is increased by 2s, but deals 40% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c4/Spr_item_rockdragon_3.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "D",
			"defender": "B",
			"ancient": "A",
        }
      },
{
        "name": "Tough Gauntlet",
        "description": "Your abilities and loot all deal 30% more damage, but all GCDs are 0.2s longer.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/fc/Spr_item_rockdragon_4.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "A",
			"spellsword": "A",
			"sniper": "S",
			"bruiser": "S",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Rockdragon Mail",
        "description": "Your movement speed is significantly reduced. Will shield you from damage for 2 seconds every 45 seconds. Starts battle on a 5 second cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/be/Spr_item_rockdragon_5.png",
        "tiers": {
			"wizard": "F",
			"assassin": "F",
			"heavyblade": "F",
			"dancer": "F",
			"druid": "F",
			"spellsword": "F",
			"sniper": "F",
			"bruiser": "F",
			"defender": "F",
			"ancient": "F",
        }
      },
{
        "name": "Obsidian Hairpin",
        "description": "Increases Special damage by 20%. Whenever you gain invulnerability, your Special has a 50% chance of resetting.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/3e/Spr_item_rockdragon_6.png",
        "tiers": {
			"wizard": "A",
			"assassin": "A",
			"heavyblade": "S",
			"dancer": "C",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "C",
			"defender": "B",
			"ancient": "A",
        }
      },
{
        "name": "Iron Greaves",
        "description": "Every 12s, standing still will grant brief invulnerability and reset your Defensive. Movement speed is slightly reduced. Starts battle on cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/b1/Spr_item_rockdragon_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "B",
			"spellsword": "B",
			"sniper": "D",
			"bruiser": "D",
			"defender": "A",
			"ancient": "F",
        }
      },
{
        "name": "Volcano Spear",
        "description": "Your Primary inflicts Burn. Deals damage upon wearing off, equal to the damage of the hit that applied burn. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/04/Spr_item_flame_0.png",
        "tiers": {
			"wizard": "A",
			"assassin": "D",
			"heavyblade": "A",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "B",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Reddragon Blade",
        "description": "Your Secondary inflicts Burn. Deals damage upon wearing off, equal to the damage of the hit that applied burn. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/35/Spr_item_flame_1.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "A",
			"bruiser": "D",
			"defender": "B",
			"ancient": "A",
        }
      },
{
        "name": "Flame Bow",
        "description": "Every 10s, fires a projectile at your targeted enemy that deals 180 damage and applies Burn. Deals damage upon wearing off, equal to the damage of the hit that applied burn. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/4e/Spr_item_flame_2.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Meteor Staff",
        "description": "Your Special inflicts Burn. Deals damage upon wearing off, equal to the damage of the hit that applied burn. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/55/Spr_item_flame_3.png",
        "tiers": {
			"wizard": "S",
			"assassin": "A",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "C",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "C",
			"defender": "A",
			"ancient": "D",
        }
      },
{
        "name": "Phoenix Charm",
        "description": "If you perish in battle, restore to full HP instead. Only works once.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/94/Spr_item_flame_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Firescale Corset",
        "description": "All of your cooldowns are reduced by 3s. If you use your Defensive, this effect ends until the end of battle.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/8d/Spr_item_flame_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "F",
			"druid": "B",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "C",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Demon Horns",
        "description": "All your abilities and loot deal 30% more damage. If you use your Defensive, this effect ends until the end of battle.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/16/Spr_item_flame_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "B",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Flamewalker Boots",
        "description": "All GCDs are shortened by 15% and your movement speed is increased significantly. If you use your Defensive, this effect ends until the end of battle.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/76/Spr_item_flame_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Diamond Shield",
        "description": "Every 25s, using your Defensive will place down a small field for 3 seconds that erases projectiles. While standing in the field, allies don't take damage. Starts battle on a 5 second cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/84/Spr_item_gem_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Peridot Rapier",
        "description": "Increases Secondary damage by 20%. Every 8s, using your Secondary will grant you brief invulnerability and erase projectiles in a large radius around you.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5e/Spr_item_gem_1.png",
        "tiers": {
			"wizard": "D",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Garnet Staff",
        "description": "Increases Special damage by 20%. Your Special will erase projectiles in a radius around you and grant brief invulnerability.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/7f/Spr_item_gem_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "S",
			"druid": "C",
			"spellsword": "S",
			"sniper": "A",
			"bruiser": "D",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Sapphire Violin",
        "description": "Every 18s, grants Elegy. Deal 30% more damage for 8 seconds to all allies. Breaks if you take damage 2 times. Starts battle on cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/15/Spr_item_gem_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Emerald Chestplate",
        "description": "The counter on this item will decrease instead of you taking damage. The counter starts at 3 on pickup.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/41/Spr_item_gem_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Amethyst Bracelet",
        "description": "Deal 30% more damage. Breaks if you take damage 3 times.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/36/Spr_item_gem_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Topaz Charm",
        "description": "Gain 8 extra Gold at the end of each fight. Breaks if you take damage 3 times.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/be/Spr_item_gem_6.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Ruby Circlet",
        "description": "Your Special deals 80% more damage. Breaks if you take damage once.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/ae/Spr_item_gem_7.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "F",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Brightstorm Spear",
        "description": "Has a 30% chance of dealing 100 damage to all enemies when your Primary does damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/2b/Spr_item_lightning_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "C",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "C",
			"defender": "A",
			"ancient": "A",
        }
      },
{
        "name": "Bolt Staff",
        "description": "Deals 150 damage to all enemies when you use your Special.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/27/Spr_item_lightning_1.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "A",
			"sniper": "A",
			"bruiser": "D",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Lightning Bow",
        "description": "Every 12s, fires a projectile at your targeted enemy that deals 300 damage. Cooldown instantly resets when a % chance succeeds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/40/Spr_item_lightning_2.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Darkstorm Knife",
        "description": "Has a 30% chance of dealing 100 damage to all enemies when your Secondary does damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5c/Spr_item_lightning_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Darkcloud Necklace",
        "description": "Damage from loot is increased by 50%.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/01/Spr_item_lightning_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "A",
			"sniper": "A",
			"bruiser": "B",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Crown of Storms",
        "description": "When a % chance succeeds, deal 200 damage to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/2b/Spr_item_lightning_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "S",
			"druid": "C",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "D",
        }
      },
{
        "name": "Thunderclap Gloves",
        "description": "All abilities have a 20% chance of dealing 200 damage to all enemies when used.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/3f/Spr_item_lightning_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Storm Petticoat",
        "description": "Deal 250 damage to all enemies when you gain invulnerability.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c5/Spr_item_lightning_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "S",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "A",
			"defender": "D",
			"ancient": "C",
        }
      },
{
        "name": "Holy Greatsword",
        "description": "Every 10s, grants you Smite. Deal 10% more damage for 10 seconds and then slice the air around you, dealing 200 damage to nearby enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/32/Spr_item_shrine_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Sacred Bow",
        "description": "Every 10s, fires a projectile at your targeted enemy that deals 250 damage. Cooldown instantly resets when you gain a buff.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a4/Spr_item_shrine_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "S",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Purification Rod",
        "description": "Every 18s, using your Primary will give you Elegy. Deal 30% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a8/Spr_item_shrine_2.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Ornamental Bell",
        "description": "Every 15s, grants Smite. Deal 10% more damage for 10 seconds to all allies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/20/Spr_item_shrine_3.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Shrinemaiden's Kosode",
        "description": "When you have a buff, your movement speed increases significantly and you deal 25% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/e3/Spr_item_shrine_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "A",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Redwhite Ribbon",
        "description": "You deal 5% more damage. Buffs you place last 50% longer.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/6a/Spr_item_shrine_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "A",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Divine Mirror",
        "description": "Every 10 times you use an ability, deal 500 damage to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/92/Spr_item_shrine_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Golden Chime",
        "description": "Every 2 times you use your Defensive, gain Elegy. Deal 30% more damage for 8 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/6d/Spr_item_shrine_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Book of Cheats",
        "description": "Your Special will have random, chaotic effects.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/42/Spr_item_lucky_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "C",
			"spellsword": "S",
			"sniper": "S",
			"bruiser": "D",
			"defender": "A",
			"ancient": "D",
        }
      },
{
        "name": "Golden Katana",
        "description": "Your Primary and Secondary have a 5% chance to deal 100 damage 5 times to a large radius around your targeted enemy when used.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/3c/Spr_item_lucky_1.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "C",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "B",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Glittering Trumpet",
        "description": "Every 20s, grant Rabbitluck to all allies for 5 seconds. Cooldown cannot be reset by ability or loot effects.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/48/Spr_item_lucky_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "A",
			"heavyblade": "C",
			"dancer": "S",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Royal Staff",
        "description": "Your Special deals extra damage based on how much gold you have (1% for every 1 gold).",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/45/Spr_item_lucky_3.png",
        "tiers": {
			"wizard": "S",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "D",
			"defender": "S",
			"ancient": "S",
        }
      },
{
        "name": "Ballroom Gown",
        "description": "Makes you slightly luckier and slightly increases your movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/94/Spr_item_lucky_4.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "C",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "D",
			"defender": "A",
			"ancient": "F",
        }
      },
{
        "name": "Silver Coin",
        "description": "On pickup, gain 30 gold.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/8d/Spr_item_lucky_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Queen's Crown",
        "description": "Critical hits now deal 175% extra damage, instead of their normal 75% extra damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/51/Spr_item_lucky_6.png",
        "tiers": {
			"wizard": "S",
			"assassin": "S",
			"heavyblade": "S",
			"dancer": "S",
			"druid": "S",
			"spellsword": "S",
			"sniper": "S",
			"bruiser": "S",
			"defender": "S",
			"ancient": "S",
        }
      },
{
        "name": "Mimick Rabbitfoot",
        "description": "Makes you significantly luckier. Not a real rabbit's foot.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/da/Spr_item_lucky_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "C",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "D",
			"defender": "A",
			"ancient": "F",
        }
      },
{
        "name": "Butterfly Ocarina",
        "description": "On pickup, heal all allies for 1. Heals all allies for 1 HP every 2 fights.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/2d/Spr_item_life_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Fairy Spear",
        "description": "Your Primary has a 30% larger radius and deals 40% more damage, but stops movement when used.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c8/Spr_item_life_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "F",
			"druid": "F",
			"spellsword": "D",
			"sniper": "B",
			"bruiser": "S",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Moss Shield",
        "description": "Every 12s, using your Defensive will reset its cooldown instantly.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5d/Spr_item_life_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",
			"defender": "A",
			"ancient": "D",
        }
      },
{
        "name": "Floral Bow",
        "description": "Every 6s, fires a projectile at your targeted enemy that deals 250 damage. Only activates while standing still.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/7f/Spr_item_life_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Blue Rose",
        "description": "Your max HP is increased by 1. Has a 50% chance of healing you for 1 and granting you 100 XP at the end of each fight.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/31/Spr_item_life_4.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Sunflower Crown",
        "description": "Your max HP is increased by 1. You become able to graze slightly into a projectile without taking damage. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/4a/Spr_item_life_5.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Midsummer Dress",
        "description": "Your max HP is increased by 1. Ability or loot effects that temporarily slow your movement no longer affect you. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d1/Spr_item_life_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "B",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Grasswoven Bracelet",
        "description": "Your max HP is increased by 1. All abilities and loot hitboxes are 30% larger. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/b1/Spr_item_life_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Snakefang Dagger",
        "description": "Your Secondary applies Poison, dealing damage once per second. Strength: 30. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/34/Spr_item_poison_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Ivy Staff",
        "description": "Your Primary applies Poison, dealCng damage once per second. Strength: 30. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c3/Spr_item_poison_1.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Deathcap Tome",
        "description": "Your Special applies Poison, dealing damage once per second. Strength: 40. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/31/Spr_item_poison_2.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Spiderbite Bow",
        "description": "Every 10s, fires a projectile at your targeted enemy that deals 50 damage and applies Poison, dealing damage once per second. Strength: 40. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/72/Spr_item_poison_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Compound Gloves",
        "description": "When you deal damage, has a 10% chance to apply Decay, dealing damage once per second. Strength: 30. Duration: 30 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/73/Spr_item_poison_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Poisonfrog Charm",
        "description": "When a % chance succeeds, apply Poison to all enemies, dealing damage once per second. Strength: 50. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c2/Spr_item_poison_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "F",
			"dancer": "B",
			"druid": "F",
			"spellsword": "F",
			"sniper": "F",
			"bruiser": "F",
			"defender": "F",
			"ancient": "F",
        }
      },
{
        "name": "Venom Hood",
        "description": "Your abilities do 15 more damage. Debuffs you place deal 50 more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c7/Spr_item_poison_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "D",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Chemist's Coat",
        "description": "Your Defensive applies Poison to nearby enemies, dealing damage once per second. Strength: 40. Duration: 8 seconds. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/46/Spr_item_poison_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Seashell Shield",
        "description": "Your Defensive has a random cooldown between 1s and 15s every time you use it.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/10/Spr_item_depth_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "S",
			"sniper": "C",
			"bruiser": "D",
			"defender": "B",
			"ancient": "F",
        }
      },
{
        "name": "Necronomicon",
        "description": "Every 8s, using your Special will reset its cooldown instantly and gain Charge. Charged attacks deal 1.5x damage when used.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/1a/Spr_item_depth_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "B",
			"druid": "S",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "A",
			"ancient": "S",
        }
      },
{
        "name": "Tidal Greatsword",
        "description": "Every 12s, slices a large radius around you dealing 200 damage. Slowly gets larger and deals more damage as a fight drags on.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/bf/Spr_item_depth_2.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Occult Dagger",
        "description": "Your Secondary is 80% more powerful, but gains 5s of cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/71/Spr_item_depth_3.png",
        "tiers": {
			"wizard": "F",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "F",
			"druid": "A",
			"spellsword": "D",
			"sniper": "A",
			"bruiser": "F",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Mermaid Scalemail",
        "description": "All cooldowns are reduced by 2s. All loot and abilities with cooldowns start battles on an 8s cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/69/Spr_item_depth_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "S",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "F",
        }
      },
{
        "name": "Hydrous Blob",
        "description": "Every 8s, using your Secondary fires an eldritch beast at your target dealing 300 damage. Starts battles on cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f8/Spr_item_depth_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Abyss Artifact",
        "description": "Every 30s, using your Defensive grants Super. Become faster, invincible, more mobile, and deal 30% more damage for 8 seconds. Starts on a 15s cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/eb/Spr_item_depth_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Lost Pendant",
        "description": "At the start of each fight, inflict all enemies with Decay, dealing damage once per second. Strength: 30. Duration: 99 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d5/Spr_item_depth_7.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Sawtooth Cleaver",
        "description": "Increases your Primary's damage by 30%, but decreases its radius by 20%.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/81/Spr_item_darkbite_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "D",
			"druid": "C",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "B",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Raven's Dagger",
        "description": "Increases your Secondary's damage by 50%, but decreases its radius by 40%.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/59/Spr_item_darkbite_1.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "D",
			"dancer": "B",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "C",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Killing Note",
        "description": "Increases your Special's damage by 30%, but decreases its radius by 20%.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/96/Spr_item_darkbite_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "A",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "D",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Blacksteel Buckler",
        "description": "Your Defensive's range decreases by 30%, but it has a 2s shorter cooldown and grants Counter. Deal 50% more damage for 3 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/52/Spr_item_darkbite_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "A",
			"defender": "B",
			"ancient": "A",
        }
      },
{
        "name": "Nightguard Gloves",
        "description": "Whichever ability has the highest base damage value deals 20% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d1/Spr_item_darkbite_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "C",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Sniper's Eyeglasses",
        "description": "You deal 30% more damage when separated from your target by at least 3 rabbitleaps.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c4/Spr_item_darkbite_5.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "D",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Darkmage Charm",
        "description": "After standing still for 1s, your Special deals 40% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/00/Spr_item_darkbite_6.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "F",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Firststrike Bracelet",
        "description": "Every 15s, gain Blackstrike. Deal 200% more damage for 3 seconds when you use your Secondary.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/7d/Spr_item_darkbite_7.png",
        "tiers": {
			"wizard": "S",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "S",
			"spellsword": "C",
			"sniper": "S",
			"bruiser": "B",
			"defender": "A",
			"ancient": "A",
        }
      },
{
        "name": "Obsidian Rod",
        "description": "Your Special's strength becomes the total cooldown time of all abilities and loot multiplied by 10, divided by hits (max 1000).",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/71/Spr_item_timegem_0.png",
        "tiers": {
			"wizard": "F",
			"assassin": "C",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "D",
			"spellsword": "B",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "F",
        }
      },
{
        "name": "Darkglass Spear",
        "description": "Your Primary's strength becomes your Special's cooldown multiplied by 30 minus your Secondary's strength, divided by hits (max 500).",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/05/Spr_item_timegem_1.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "F",
			"dancer": "S",
			"druid": "A",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "A",
			"defender": "F",
			"ancient": "S",
        }
      },
{
        "name": "Timespace Dagger",
        "description": "Your Secondary's strength becomes the combined cooldown of Special and Defensive multiplied by 10, divided by hits (max 500).",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/ae/Spr_item_timegem_2.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "S",
			"druid": "D",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "A",
			"defender": "D",
			"ancient": "C",
        }
      },
{
        "name": "Quartz Shield",
        "description": "Your Defensive's cooldown becomes 30s. When a loot item activates, reduce the remaining Defensive cooldown by that amount.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/31/Spr_item_timegem_3.png",
        "tiers": {
			"wizard": "F",
			"assassin": "F",
			"heavyblade": "F",
			"dancer": "D",
			"druid": "F",
			"spellsword": "F",
			"sniper": "F",
			"bruiser": "F",
			"defender": "C",
			"ancient": "F",
        }
      },
{
        "name": "Pocketwatch",
        "description": "Abilities with a GCD of 1.1s or less deal 30% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d4/Spr_item_timegem_4.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "S",
			"sniper": "C",
			"bruiser": "S",
			"defender": "D",
			"ancient": "C",
        }
      },
{
        "name": "Nova Crown",
        "description": "Your Special's cooldown becomes 30s. Every 8s, reduce it to 1s and gain Charge. Charged attacks deal 1.5x damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/8d/Spr_item_timegem_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "B",
			"druid": "S",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "C",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Blackhole Charm",
        "description": "Deal 200 damage to all enemies when using an ability or loot with a cooldown of 10s or more. Hits extra times for longer cooldowns (max 5).",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/ea/Spr_item_timegem_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "S",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "A",
        }
      },
{
        "name": "Twinstar Earrings",
        "description": "Your Primary and Secondary now have a 2s GCD and deal 70% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/e9/Spr_item_timegem_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "B",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "S",
			"defender": "A",
			"ancient": "D",
        }
      },
{
        "name": "Kyou No Omikuji",
        "description": "All damage you deal increases by 50%. % chance triggers and critical hits no longer occur.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/73/Spr_item_youkai_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "F",
			"heavyblade": "C",
			"dancer": "F",
			"druid": "C",
			"spellsword": "D",
			"sniper": "C",
			"bruiser": "D",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Youkai Bracelet",
        "description": "All damage you deal increases by 40%. Damage is no longer randomized and cannot crit.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/e5/Spr_item_youkai_1.png",
        "tiers": {
			"wizard": "F",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "B",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Oni Staff",
        "description": "Your Special deals 30% more damage. When a % chance succeeds, it goes on an 8s cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/6c/Spr_item_youkai_2.png",
        "tiers": {
			"wizard": "F",
			"assassin": "F",
			"heavyblade": "C",
			"dancer": "F",
			"druid": "C",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "F",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Kappa Shield",
        "description": "Your Defensive has a 3s shorter cooldown, but can no longer be reset.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5b/Spr_item_youkai_3.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "S",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Usagi Kamen",
        "description": "When a % chance succeeds, gain a random buff for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f5/Spr_item_youkai_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "S",
			"heavyblade": "D",
			"dancer": "S",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Red Tanzaku",
        "description": "Miracles occasionally happen.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/95/Spr_item_youkai_5.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Vega Spear",
        "description": "Your Primary deals 70% more damage but gains a 7s cooldown. When a % chance succeeds, the cooldown resets.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/09/Spr_item_youkai_6.png",
        "tiers": {
			"wizard": "F",
			"assassin": "C",
			"heavyblade": "F",
			"dancer": "D",
			"druid": "F",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "F",
			"defender": "C",
			"ancient": "D",
        }
      },
{
        "name": "Altair Dagger",
        "description": "Your Secondary deals 30% more damage but has a 3s GCD. When used, it has a 90% chance to instead have a 1s GCD.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/36/Spr_item_youkai_7.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "D",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Ghost Spear",
        "description": "Your Primary now only deals 10 damage, and applies Ghostflame, dealing damage when applied and upon wearing off. Strength: 250. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/7d/Spr_item_haunted_0.png",
        "tiers": {
			"wizard": "F",
			"assassin": "F",
			"heavyblade": "F",
			"dancer": "B",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "F",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Phantom Dagger",
        "description": "Your Secondary now only deals 10 damage, and applies Ghostflame, dealing damage when applied and upon wearing off. Strength: 250. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/dc/Spr_item_haunted_1.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "A",
			"dancer": "D",
			"druid": "D",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Cursed Candlestaff",
        "description": "Your Special now only deals 10 damage, and applies Ghostflame, dealing damage when applied and upon wearing off. Strength: 350. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c4/Spr_item_haunted_2.png",
        "tiers": {
			"wizard": "F",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "F",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "S",
			"defender": "C",
			"ancient": "F",
        }
      },
{
        "name": "Haunted Gloves",
        "description": "Abilities and loot that hit for 100 damage or less now hit for exactly 100 damage, regardless of other loot effects.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/26/Spr_item_haunted_3.png",
        "tiers": {
			"wizard": "F",
			"assassin": "S",
			"heavyblade": "F",
			"dancer": "S",
			"druid": "D",
			"spellsword": "F",
			"sniper": "F",
			"bruiser": "C",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Old Bonnet",
        "description": "Abilities and loot that hit once now deal 250 damage, regardless of other loot effects or ability effects.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/87/Spr_item_haunted_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "F",
			"druid": "B",
			"spellsword": "B",
			"sniper": "A",
			"bruiser": "A",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Maid Outfit",
        "description": "When you gain invulnerability, afflict surrounding enemies with Ghostflame, dealing damage when applied and upon wearing off for 5 seconds. Slightly increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a4/Spr_item_haunted_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "S",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "S",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Calling Bell",
        "description": "Every 12s, afflict surrounding enemies with Ghostflame, dealing damage when applied and upon wearing off for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/62/Spr_item_haunted_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Smoke Shield",
        "description": "Every 24s, your Defensive grants Ghost, causing you to disappear and evade attacks until you use an attack. Slows movement and increases damage dealt by 60% for 5 seconds. Your Secondary no longer breaks Vanish. Starts battle on a 5 second cooldown.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/57/Spr_item_haunted_7.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "C",
        }
      },
{
        "name": "Grandmaster Spear",
        "description": "Your Primary's damage increases by 40%. Your Special's cooldown increases by 4 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/50/Spr_item_gladiator_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "D",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "B",
			"defender": "C",
			"ancient": "D",
        }
      },
{
        "name": "Teacher Knife",
        "description": "Your Secondary's damage increases by 40%. Adds 2 seconds of cooldown to your Primary.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c9/Spr_item_gladiator_1.png",
        "tiers": {
			"wizard": "F",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "A",
			"druid": "B",
			"spellsword": "D",
			"sniper": "S",
			"bruiser": "F",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Tactician Rod",
        "description": "Your Special's damage increases by 30%. Adds 2 seconds of cooldown to your Secondary.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/12/Spr_item_gladiator_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "B",
			"spellsword": "A",
			"sniper": "S",
			"bruiser": "F",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Spiked Shield",
        "description": "When an ability or loot effect erases projectiles in a radius around you, deal 300 damage to that radius as well.",
        "imageUrl": "https://static.wikitide.net/rnswiki/0/07/Spr_item_gladiator_3.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "C",
			"spellsword": "S",
			"sniper": "F",
			"bruiser": "D",
			"defender": "S",
			"ancient": "C",
        }
      },
{
        "name": "Battlemaiden Armor",
        "description": "Using your Defensive will reset loot and ability cooldowns with less than 8 seconds remaining.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/3e/Spr_item_gladiator_4.png",
        "tiers": {
			"wizard": "A",
			"assassin": "A",
			"heavyblade": "C",
			"dancer": "F",
			"druid": "C",
			"spellsword": "B",
			"sniper": "D",
			"bruiser": "A",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Gladiator Helmet",
        "description": "Abilities and loot that have cooldowns deal 20% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/ae/Spr_item_gladiator_5.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "A",
			"sniper": "C",
			"bruiser": "D",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Lancer Gauntlets",
        "description": "All damage is increased by 30%. Your Primary and Secondary gain cooldowns of 2 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d1/Spr_item_gladiator_6.png",
        "tiers": {
			"wizard": "F",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "S",
			"druid": "B",
			"spellsword": "B",
			"sniper": "S",
			"bruiser": "F",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Lion Charm",
        "description": "Deal 180 damage to nearby enemies when an ability or loot with a cooldown is activated.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/ad/Spr_item_gladiator_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "C",
			"spellsword": "S",
			"sniper": "S",
			"bruiser": "C",
			"defender": "B",
			"ancient": "S",
        }
      },
{
        "name": "Bluebolt Staff",
        "description": "Your Primary applies Spark, dealing damage to all enemies once per second. Strength: 20. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/ee/Spr_item_sparkblade_0.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Lapis Sword",
        "description": "Your Secondary applies Spark, dealing damage to all enemies once per second. Strength: 20. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/9b/Spr_item_sparkblade_1.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Shockwave Tome",
        "description": "Your Special applies Spark, dealing damage to all enemies once per second. Strength: 30. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5f/Spr_item_sparkblade_2.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Battery Shield",
        "description": "Every 30 times you or debuffs you apply deal damage to an enemy, your Defensive's cooldown resets.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/75/Spr_item_sparkblade_3.png",
        "tiers": {
			"wizard": "C",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "B",
			"spellsword": "S",
			"sniper": "D",
			"bruiser": "F",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Raiju Crown",
        "description": "Every 20 times you or debuffs you apply deal damage to an enemy, apply Spark to all enemies, dealing damage once per second. Strength: 40. Duration: 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/21/Spr_item_sparkblade_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "C",
			"heavyblade": "D",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Staticshock Earrings",
        "description": "Every 10 times you or debuffs you apply deal damage to an enemy, deal 150 damage to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/5d/Spr_item_sparkblade_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Stormdance Gown",
        "description": "Every 40 times you or debuffs you apply deal damage to an enemy, gain invulnerability for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/34/Spr_item_sparkblade_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "F",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Blackbolt Ribbon",
        "description": "Every 50 times you or debuffs you apply deal damage to an enemy, deal 1200 damage to all enemies.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d9/Spr_item_sparkblade_7.png",
        "tiers": {
			"wizard": "C",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "B",
			"spellsword": "A",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Crane Katana",
        "description": "Every time you move 15 rabbitleaps, gain Flow-Str. Your Primary deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/7/7b/Spr_item_swiftflight_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "A",
			"heavyblade": "S",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "A",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Falconfeather Dagger",
        "description": "Every time you move 15 rabbitleaps, gain Flow-Dex. Your Secondary deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/38/Spr_item_swiftflight_1.png",
        "tiers": {
			"wizard": "F",
			"assassin": "A",
			"heavyblade": "D",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "C",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Tornado Staff",
        "description": "Every time you move 15 rabbitleaps, gain Flow-Int. Your Special deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/aa/Spr_item_swiftflight_2.png",
        "tiers": {
			"wizard": "A",
			"assassin": "A",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "D",
			"defender": "B",
			"ancient": "A",
        }
      },
{
        "name": "Cloud Guard",
        "description": "Every time you move 25 rabbitleaps, gain invulnerability for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/30/Spr_item_swiftflight_3.png",
        "tiers": {
			"wizard": "F",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "C",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Hermes Bow",
        "description": "Every 10s, fires a projectile at your targeted enemy that deals 250 damage. Cooldown resets every time you move 10 rabbitleaps.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/c5/Spr_item_swiftflight_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Talon Charm",
        "description": "Deals 150 damage to all enemies every time you move 5 rabbitleaps.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/be/Spr_item_swiftflight_5.png",
        "tiers": {
			"wizard": "C",
			"assassin": "S",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "B",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Tiny Wings",
        "description": "Dramatically increases movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/3/35/Spr_item_swiftflight_6.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "C",
			"ancient": "D",
        }
      },
{
        "name": "Feathered Overcoat",
        "description": "Maxes out your movement speed while you are invulnerable.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/b4/Spr_item_swiftflight_7.png",
        "tiers": {
			"wizard": "F",
			"assassin": "D",
			"heavyblade": "F",
			"dancer": "F",
			"druid": "F",
			"spellsword": "F",
			"sniper": "F",
			"bruiser": "F",
			"defender": "F",
			"ancient": "F",
        }
      },
{
        "name": "Sandpriestess Spear",
        "description": "Your Primary has a 40% chance to grant Flash-Dex. Your next Secondary deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/e2/Spr_item_sacredflame_0.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "B",
			"spellsword": "D",
			"sniper": "B",
			"bruiser": "D",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Flamedancer Dagger",
        "description": "Your Secondary has a 40% chance to grant Flash-Str. Your next Primary deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/55/Spr_item_sacredflame_1.png",
        "tiers": {
			"wizard": "C",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "A",
			"druid": "C",
			"spellsword": "D",
			"sniper": "A",
			"bruiser": "C",
			"defender": "A",
			"ancient": "C",
        }
      },
{
        "name": "Whiteflame Staff",
        "description": "Every 2 times you use your Special, gain Flash-Str. Your next Primary deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/cf/Spr_item_sacredflame_2.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "C",
			"spellsword": "B",
			"sniper": "S",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Sacred Shield",
        "description": "Every 2 times you use your Defensive, gain Flash-Int. Your next Special deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/89/Spr_item_sacredflame_3.png",
        "tiers": {
			"wizard": "D",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",
			"defender": "C",
			"ancient": "B",
        }
      },
{
        "name": "Marble Clasp",
        "description": "Every 5 times you use an ability, gain Flash-Dex. Your next Secondary deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/8a/Spr_item_sacredflame_4.png",
        "tiers": {
			"wizard": "D",
			"assassin": "B",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "B",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Sun Pendant",
        "description": "Every 10 times you use an ability, reset your Special's cooldown and gain Flash-Int. Your next Special deals 150% more damage for 5 seconds. Wears off when you use an attack.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/66/Spr_item_sacredflame_5.png",
        "tiers": {
			"wizard": "A",
			"assassin": "S",
			"heavyblade": "S",
			"dancer": "B",
			"druid": "A",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "C",
			"defender": "A",
			"ancient": "S",
        }
      },
{
        "name": "Tiny Hourglass",
        "description": "Every 12s, deal 120 damage to all enemies. Damage increases by 120 each time this activates.",
        "imageUrl": "https://static.wikitide.net/rnswiki/4/4a/Spr_item_sacredflame_6.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "B",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "B",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Desert Earrings",
        "description": "Every time you gain a buff, gain another random buff for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/25/Spr_item_sacredflame_7.png",
        "tiers": {
			"wizard": "A",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "S",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Giant Stone Club",
        "description": "Your Primary deals 70% more damage. Its GCD is increased by 0.6s. Your movement speed is moderately reduced.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/12/Spr_item_ruins_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "D",
			"druid": "C",
			"spellsword": "D",
			"sniper": "B",
			"bruiser": "S",
			"defender": "B",
			"ancient": "D",
        }
      },
{
        "name": "Ruins Sword",
        "description": "Your Secondary deals 100% more damage. Its GCD is increased by 0.8s. Your movement speed is slightly reduced.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/96/Spr_item_ruins_1.png",
        "tiers": {
			"wizard": "F",
			"assassin": "S",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "A",
			"spellsword": "D",
			"sniper": "B",
			"bruiser": "A",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Mountain Staff",
        "description": "Your Special deals 200% more damage. Its GCD is increased by 2.5s. Your movement speed is moderately reduced.",
        "imageUrl": "https://static.wikitide.net/rnswiki/a/a5/Spr_item_ruins_2.png",
        "tiers": {
			"wizard": "S",
			"assassin": "B",
			"heavyblade": "A",
			"dancer": "A",
			"druid": "S",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "A",
			"ancient": "S",
        }
      },
{
        "name": "Boulder Shield",
        "description": "Every 30s, using your Defensive grants all allies Stoneskin, shielding them from damage once. Erases bullets in a radius upon wearing off. Duration: 5 seconds. Starts battle off cooldown. Slightly reduces movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/b/b9/Spr_item_ruins_3.png",
        "tiers": {
			"wizard": "D",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "D",
			"druid": "D",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "D",
			"defender": "D",
			"ancient": "D",
        }
      },
{
        "name": "Golem's Claymore",
        "description": "Every 20s, grants Stoneskin, shielding you from damage once. Erases bullets in a radius upon wearing off, then slices the air dealing 500 damage to nearby enemies. Duration: 5 seconds. Slightly reduces movement speed.",
        "imageUrl": "https://static.wikitide.net/rnswiki/2/2c/Spr_item_ruins_4.png",
        "tiers": {
			"wizard": "C",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Stoneplate Armor",
        "description": "Start each battle with Graniteskin, shielding you from damage once. Slows movement dramatically and increases damage by 20%. Duration lasts until hit.",
        "imageUrl": "https://static.wikitide.net/rnswiki/d/d1/Spr_item_ruins_5.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "B",
			"druid": "C",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "S",
			"defender": "C",
			"ancient": "C",
        }
      },
{
        "name": "Sacredstone Charm",
        "description": "Abilities with a GCD equal to or higher than 1.5s deal 50% more damage.",
        "imageUrl": "https://static.wikitide.net/rnswiki/6/60/Spr_item_ruins_6.png",
        "tiers": {
			"wizard": "C",
			"assassin": "D",
			"heavyblade": "C",
			"dancer": "D",
			"druid": "S",
			"spellsword": "C",
			"sniper": "A",
			"bruiser": "D",
			"defender": "S",
			"ancient": "D",
        }
      },
{
        "name": "Clay Rabbit",
        "description": "Every 12s, standing still grants Stoneskin, shielding you from damage once. Erases bullets in a radius upon wearing off. Duration: 3 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/e/e9/Spr_item_ruins_7.png",
        "tiers": {
			"wizard": "B",
			"assassin": "D",
			"heavyblade": "D",
			"dancer": "A",
			"druid": "B",
			"spellsword": "B",
			"sniper": "B",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Waterfall Polearm",
        "description": "Every 10s, when you use your Primary, gain Flow-Str. Your Primary deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/92/Spr_item_lakeshrine_0.png",
        "tiers": {
			"wizard": "B",
			"assassin": "B",
			"heavyblade": "S",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "S",
			"bruiser": "S",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Vorpal Dao",
        "description": "Every 10s, when you use your Secondary, gain Flow-Dex. Your Secondary deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/84/Spr_item_lakeshrine_1.png",
        "tiers": {
			"wizard": "D",
			"assassin": "B",
			"heavyblade": "D",
			"dancer": "C",
			"druid": "C",
			"spellsword": "D",
			"sniper": "D",
			"bruiser": "C",
			"defender": "B",
			"ancient": "B",
        }
      },
{
        "name": "Jade Staff",
        "description": "Every 2 times you use your Special, gain Tranquility, dealing 30% more damage. Wears off if you move too far. Duration: 10 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/9/9a/Spr_item_lakeshrine_2.png",
        "tiers": {
			"wizard": "D",
			"assassin": "C",
			"heavyblade": "F",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "D",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Reflection Shield",
        "description": "When you erase projectiles in a radius around you, gain Counter, dealing 50% more damage. Wears off when you use an attack. Duration: 3 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/f/f7/Spr_item_lakeshrine_3.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "A",
			"dancer": "D",
			"druid": "C",
			"spellsword": "C",
			"sniper": "A",
			"bruiser": "B",
			"defender": "S",
			"ancient": "B",
        }
      },
{
        "name": "Butterfly Hairpin",
        "description": "When you gain invincibility, gain a random buff for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/c/ce/Spr_item_lakeshrine_4.png",
        "tiers": {
			"wizard": "B",
			"assassin": "S",
			"heavyblade": "S",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "B",
			"bruiser": "S",
			"defender": "B",
			"ancient": "C",
        }
      },
{
        "name": "Watermage Pendant",
        "description": "Every 12s, when you stand still, gain Flow-Int. Your Special deals 70% more damage for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/8/83/Spr_item_lakeshrine_5.png",
        "tiers": {
			"wizard": "A",
			"assassin": "B",
			"heavyblade": "B",
			"dancer": "D",
			"druid": "A",
			"spellsword": "A",
			"sniper": "B",
			"bruiser": "D",
			"defender": "A",
			"ancient": "B",
        }
      },
{
        "name": "Raindrop Earrings",
        "description": "Every 18s, when you stand still, gain Repeat. Your Special's cooldown instantly resets upon use for 5 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/1/1a/Spr_item_lakeshrine_6.png",
        "tiers": {
			"wizard": "B",
			"assassin": "C",
			"heavyblade": "B",
			"dancer": "C",
			"druid": "A",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "D",
			"defender": "A",
			"ancient": "A",
        }
      },
{
        "name": "Aquamarine Bracelet",
        "description": "Every 12s, gain a random buff for 10 seconds.",
        "imageUrl": "https://static.wikitide.net/rnswiki/5/50/Spr_item_lakeshrine_7.png",
        "tiers": {
			"wizard": "A",
			"assassin": "C",
			"heavyblade": "C",
			"dancer": "C",
			"druid": "C",
			"spellsword": "C",
			"sniper": "C",
			"bruiser": "C",
			"defender": "B",
			"ancient": "C",
        }
      }].sort((a, b) => a.name.localeCompare(b.name));

    